on:
  push:
    branches:
      - main
  pull_request: {}

name: Test

jobs:
  build_and_test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: supplypike/setup-bin@v3
        with:
          uri: 'https://github.com/calcit-lang/calcit/releases/download/0.6.23/cr'
          name: 'cr'
          version: '0.6.23'

      - uses: supplypike/setup-bin@v3
        with:
          uri: 'https://github.com/calcit-lang/calcit/releases/download/0.6.23/caps'
          name: 'caps'
          version: '0.6.23'

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: cargo build --release

      - run: mkdir dylibs/ && ls target/release/ && cp -v target/release/*.* dylibs/

      - run: cr -1
